name: integration-tests
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run integration tests
        run: docker-compose -f docker-compose.test.yaml up --build --abort-on-container-exit --exit-code-from test-agent